### PR TITLE
CAL-2656: handling types TIME_WITH_TIMEZONE and TIMESTAMP_WITH_TIMEZONE as allowed cursor types in SnowflakeSourceOperations

### PR DESCRIPTION
**Pull request by giacomo-calixa**
## What
See issue https://github.com/airbytehq/airbyte/issues/23103
which impacts us with https://linear.app/calixa/issue/CAL-2656/happy-scribe-snowflake-sync-failing

## How
Added handling for cursor types TIME_WITH_TIMEZONE and TIMESTAMP_WITH_TIMEZONE as allowed in `SnowflakeSourceOperations`. Also added code to set the cursor type in the SQL statement (`io.airbyte.integrations.source.snowflake.SnowflakeSourceOperations#setCursorField`)

## Recommended reading order
1. `x.java`
2. `y.python`

## 🚨 User Impact 🚨
Are there any breaking changes? What is the end result perceived by the user? If yes, please merge this PR with the 🚨🚨 emoji so changelog authors can further highlight this if needed.

## Pre-merge Checklist
Expand the relevant checklist and delete the others.

<details><summary><strong>New Connector</strong></summary>

### Community member or Airbyter

- [ ] **Community member?** Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret`
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - [ ] `docs/integrations/README.md`
    - [ ] `airbyte-integrations/builds.md`
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)
- [ ] After the connector is published, connector added to connector index as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
- [ ] Seed specs have been re-generated by building the platform and committing the changes to the seed spec files, as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)

</details>

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- [ ] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret`
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub and connector version bumped by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)

</details>

<details><summary><strong>Connector Generator</strong></summary>

- [ ] Issue acceptance criteria met
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/issues-and-pull-requests)
- [ ] If adding a new generator, add it to the [list of scaffold modules being tested](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connector-templates/generator/build.gradle#L41)
- [ ] The generator test modules (all connectors with `-scaffold` in their name) have been updated with the latest scaffold by running `./gradlew :airbyte-integrations:connector-templates:generator:testScaffoldTemplates` then checking in your changes
- [ ] Documentation which references the generator is updated as needed

</details>

## Tests

<details><summary><strong>Unit</strong></summary>

*Put your unit tests output here.*

</details>

<details><summary><strong>Integration</strong></summary>

*Put your integration tests output here.*

</details>

<details><summary><strong>Acceptance</strong></summary>

*Put your acceptance tests output here.*

</details>

### CODE REVIEW

**Comment by giacomo-calixa** [comment]
@lgomezm @Kopiczek,

I would appreciate if you could let me know how to test this in staging or some documentation that can help me in doing so.

Thanks!

**Comment by lgomezm** [comment]
Sure. I usually build custom images for Python-based connectors, but I think we also did it once for PubSub (which is written in Java). To do that, you can do this:
1. Go to `airbyte/airbyte-integrations/connectors/source-snowflake`
2. Run `docker build . -t airbyte/source-snowflake:dev`
3. Run `docker tag airbyte/source-snowflake:dev gcr.io/calixa-cloudbuild-5a1f/airbyte-snowflake-connector:0.1.0`
4. Run `docker push gcr.io/calixa-cloudbuild-5a1f/airbyte-snowflake-connector:0.1.0`

Then you can install it in staging to test.

**Comment by giacomo-calixa** [comment]
I run:
- `./airbyte-integrations/bases/base$ docker build . -t airbyte/integration-base:dev`
- `./airbyte-integrations/bases/base-java$ docker build . -t airbyte/integration-base-java:dev`
- `./airbyte-integrations/connectors/source-snowflake$ ../../../gradlew build`
- `./airbyte-integrations/connectors/source-snowflake$ docker build -t airbyte/source-snowflake:dev .`
- `docker tag airbyte/source-snowflake:dev gcr.io/calixa-cloudbuild-5a1f/airbyte-snowflake-connector:0.1.29`
- `docker push gcr.io/calixa-cloudbuild-5a1f/airbyte-snowflake-connector:0.1.29`

**Comment by giacomo-calixa** [comment]
This PR is live as part of `gcr.io/calixa-cloudbuild-5a1f/airbyte-snowflake-connector:0.1.29` and connection http://localhost:9876/workspaces/49e0c231-af47-46eb-a87c-2fb72aa8b238/connections/273a00e3-61ba-437f-8928-cab8754927d0

@lgomezm what should I do with this PR? Should I still merge it?
Thanks

**Comment by lgomezm** [comment]
Hi @giacomo-calixa. If this is working as expected, which I think it is, you can submit this PR to Airbyte HQ, so that they adopt these changes and release an official version of the connector. Feel free to send them a PR 🚀 : https://github.com/airbytehq/airbyte/pulls

**Comment by giacomo-calixa** [comment]
> Hi @giacomo-calixa. If this is working as expected, which I think it is, you can submit this PR to Airbyte HQ, so that they adopt these changes and release an official version of the connector. Feel free to send them a PR rocket : https://github.com/airbytehq/airbyte/pulls

OK thanks will do that

**Comment by giacomo-calixa** [comment]
Turns out the Snowflake driver does not know how to interpret `OffsetDateTime` objects.
I'm attempting to convert that to Timestamp and letting the driver know to treat it as a `TIMESTAMP WITH LOCAL TIME ZONE`

**Comment by lgomezm** [comment]
It's working now! 🎉 
Screenshot 2023-02-28 at 8 02 38 AM

**Pull request closed without merging**
